spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(5pfwrN0yynUVOPbL1BfY8AbW5/liB71JsMTE9CevIek0vMr446B1wWqYuiK/IolS)
    username: ENC(9fGDku8hYt7aQeI3Id55xA==)
    password: ENC(+MdihZDyR+CJcFIXeLydIQ==)
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #useGlobalDataSourceStat=true # 合并多个DruidDataSource的监控数据
  rabbitmq:
    addresses: ENC(7YHQty028wZCP6oNSrdaX7J2Bio1s+U+GPZsxcZvjIpS56v1CmUNYV0sAEX0lSOLL5mMAbY07PFg+aupRz21rZF2E8gkSLnsWC/nydd4Fac7xmHl4JdL+Sz47gVnQO0u)
    username: ENC(SdiKugJdDr7Oa58gR6IT6xEJQBcSI4Rb)
    password: ENC(h/secgaoa+2+cBMDky2lfwIvwf+n1qTKCu9XdWJHxObCS2tPdpZC0fIP7RQYLcie)
mybatis:
  type-aliases-package: com.seesea.gateway.entity.po
  mapper-locations: classpath:mybatis/*.xml
mapper:
  mappers: com.seesea.gateway.BaseMapper
  not-empty: false
  identity: MYSQL
#刷新
management:
  endpoint:
    bus-refresh:
      enabled: true

zuul:
  routes:
    gateway:
      path: /gateway/**
      serviceId: seesea-gateway
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000